<?php

namespace Database\Seeders;

use App\Models\SportType;
use Illuminate\Database\Seeder;

class SportTypeSeeder extends Seeder
{
    /**
     * Platform-independent sport types. 'name' is the stable machine
     * key (unique), 'label' is the human-friendly display text.
     * Add to this list as new sports are needed (e.g. when Garmin
     * support is added), existing rows are left untouched, matched
     * on name.
     */
    protected array $sportTypes = [
        ['name' => 'aerobics', 'label' => 'Aerobics'],
        ['name' => 'dog-agility', 'label' => 'Dog agility'],
        ['name' => 'football', 'label' => 'Football'],
        ['name' => 'aqua-fitness', 'label' => 'Aqua fitness'],
        ['name' => 'backcountry-skiing', 'label' => 'Backcountry skiing'],
        ['name' => 'badminton', 'label' => 'Badminton'],
        ['name' => 'ballet', 'label' => 'Ballet'],
        ['name' => 'ballroom', 'label' => 'Ballroom'],
        ['name' => 'baseball', 'label' => 'Baseball'],
        ['name' => 'basketball', 'label' => 'Basketball'],
        ['name' => 'beach-tennis', 'label' => 'Beach tennis'],
        ['name' => 'beach-volley', 'label' => 'Beach volley'],
        ['name' => 'biathlon', 'label' => 'Biathlon'],
        ['name' => 'body-and-mind', 'label' => 'Body&Mind'],
        ['name' => 'bootcamp', 'label' => 'Bootcamp'],
        ['name' => 'boxing', 'label' => 'Boxing'],
        ['name' => 'calisthenics', 'label' => 'Calisthenics'],
        ['name' => 'circuit-training', 'label' => 'Circuit training'],
        ['name' => 'core', 'label' => 'Core'],
        ['name' => 'cricket', 'label' => 'Cricket'],
        ['name' => 'cross-trainer', 'label' => 'Cross-trainer'],
        ['name' => 'cross-country-running', 'label' => 'Cross-country running'],
        ['name' => 'skiing', 'label' => 'Skiing'],
        ['name' => 'cycling', 'label' => 'Cycling'],
        ['name' => 'climbing', 'label' => 'Climbing'],
        ['name' => 'curling', 'label' => 'Curling'],
        ['name' => 'dancing', 'label' => 'Dancing'],
        ['name' => 'downhill-skiing', 'label' => 'Downhill skiing'],
        ['name' => 'duathlon', 'label' => 'Duathlon'],
        ['name' => 'running', 'label' => 'Running'],
        ['name' => 'electric-biking', 'label' => 'Electric biking'],
        ['name' => 'esports', 'label' => 'Esports'],
        ['name' => 'field-hockey', 'label' => 'Field hockey'],
        ['name' => 'finnish-baseball', 'label' => 'Finnish baseball'],
        ['name' => 'fitness-boxing', 'label' => 'Fitness boxing'],
        ['name' => 'fitness-dancing', 'label' => 'Fitness dancing'],
        ['name' => 'fitness-martial-arts', 'label' => 'Fitness martial arts'],
        ['name' => 'fitness-racing', 'label' => 'Fitness Racing'],
        ['name' => 'step-workout', 'label' => 'Step workout'],
        ['name' => 'floorball', 'label' => 'Floorball'],
        ['name' => 'multisport', 'label' => 'Multisport'],
        ['name' => 'disc-golf', 'label' => 'Disc golf'],
        ['name' => 'functional-training', 'label' => 'Functional training'],
        ['name' => 'futsal', 'label' => 'Futsal'],
        ['name' => 'golf', 'label' => 'Golf'],
        ['name' => 'gravel-cycling', 'label' => 'Gravel cycling'],
        ['name' => 'group-exercise', 'label' => 'Group exercise'],
        ['name' => 'gymnastics', 'label' => 'Gymnastics'],
        ['name' => 'handball', 'label' => 'Handball'],
        ['name' => 'high-intensity-interval-training', 'label' => 'High-intensity interval training'],
        ['name' => 'hiking', 'label' => 'Hiking'],
        ['name' => 'ice-hockey', 'label' => 'Ice hockey'],
        ['name' => 'ice-skating', 'label' => 'Ice skating'],
        ['name' => 'indoor-cycling', 'label' => 'Indoor cycling'],
        ['name' => 'indoor-rowing', 'label' => 'Indoor rowing'],
        ['name' => 'inline-skating', 'label' => 'Inline skating'],
        ['name' => 'jazz', 'label' => 'Jazz'],
        ['name' => 'jogging', 'label' => 'Jogging'],
        ['name' => 'judo', 'label' => 'Judo'],
        ['name' => 'rope-skipping', 'label' => 'Rope skipping'],
        ['name' => 'kettlebell', 'label' => 'Kettlebell'],
        ['name' => 'kickbiking', 'label' => 'Kickbiking'],
        ['name' => 'kickboxing', 'label' => 'Kickboxing'],
        ['name' => 'latin', 'label' => 'Latin'],
        ['name' => 'les-mills-barre', 'label' => 'LES MILLS BARRE'],
        ['name' => 'les-mills-bodyattack', 'label' => 'LES MILLS BODYATTACK'],
        ['name' => 'les-mills-bodybalance', 'label' => 'LES MILLS BODYBALANCE'],
        ['name' => 'les-mills-bodycombat', 'label' => 'LES MILLS BODYCOMBAT'],
        ['name' => 'les-mills-bodyjam', 'label' => 'LES MILLS BODYJAM'],
        ['name' => 'les-mills-bodypump', 'label' => 'LES MILLS BODYPUMP'],
        ['name' => 'les-mills-bodystep', 'label' => 'LES MILLS BODYSTEP'],
        ['name' => 'les-mills-cxworx', 'label' => 'LES MILLS CXWORX'],
        ['name' => 'les-mills-grit-athletic', 'label' => 'LES MILLS GRIT Athletic'],
        ['name' => 'les-mills-grit-cardio', 'label' => 'LES MILLS GRIT Cardio'],
        ['name' => 'les-mills-grit-strength', 'label' => 'LES MILLS GRIT Strength'],
        ['name' => 'les-mills-rpm', 'label' => 'LES MILLS RPM'],
        ['name' => 'les-mills-shbam', 'label' => 'LES MILLS SH\'BAM'],
        ['name' => 'les-mills-sprint', 'label' => 'LES MILLS SPRINT'],
        ['name' => 'les-mills-tone', 'label' => 'LES MILLS TONE'],
        ['name' => 'les-mills-trip', 'label' => 'LES MILLS TRIP'],
        ['name' => 'mobility-dynamic', 'label' => 'Mobility (dynamic)'],
        ['name' => 'mobility-static', 'label' => 'Mobility (static)'],
        ['name' => 'modern', 'label' => 'Modern'],
        ['name' => 'car-racing', 'label' => 'Car racing'],
        ['name' => 'enduro', 'label' => 'Enduro'],
        ['name' => 'hard-enduro', 'label' => 'Hard Enduro'],
        ['name' => 'motocross', 'label' => 'Motocross'],
        ['name' => 'road-racing', 'label' => 'Road racing'],
        ['name' => 'snocross', 'label' => 'Snocross'],
        ['name' => 'mountain-biking', 'label' => 'Mountain biking'],
        ['name' => 'nordic-walking', 'label' => 'Nordic walking'],
        ['name' => 'obstacle-course-racing', 'label' => 'Obstacle course racing'],
        ['name' => 'off-road-duathlon', 'label' => 'Off-road duathlon'],
        ['name' => 'trail-running', 'label' => 'Trail running'],
        ['name' => 'off-road-triathlon', 'label' => 'Off-road triathlon'],
        ['name' => 'open-water-swimming', 'label' => 'Open water swimming'],
        ['name' => 'orienteering', 'label' => 'Orienteering'],
        ['name' => 'mountain-bike-orienteering', 'label' => 'Mountain bike orienteering'],
        ['name' => 'ski-orienteering', 'label' => 'Ski orienteering'],
        ['name' => 'other-indoor', 'label' => 'Other indoor'],
        ['name' => 'other-outdoor', 'label' => 'Other outdoor'],
        ['name' => 'padel-racing', 'label' => 'Padel racing'],
        ['name' => 'handcycling', 'label' => 'Handcycling'],
        ['name' => 'sled-hockey', 'label' => 'Sled hockey'],
        ['name' => 'adaptive-water-skiing', 'label' => 'Adaptive water skiing'],
        ['name' => 'wheelchair-racing', 'label' => 'Wheelchair racing'],
        ['name' => 'wheelchair-basketball', 'label' => 'Wheelchair basketball'],
        ['name' => 'wheelchair-tennis', 'label' => 'Wheelchair tennis'],
        ['name' => 'pickleball', 'label' => 'Pickleball'],
        ['name' => 'pilates', 'label' => 'Pilates'],
        ['name' => 'pool-swimming', 'label' => 'Pool swimming'],
        ['name' => 'riding', 'label' => 'Riding'],
        ['name' => 'ringette', 'label' => 'Ringette'],
        ['name' => 'road-cycling', 'label' => 'Road cycling'],
        ['name' => 'road-running', 'label' => 'Road running'],
        ['name' => 'roller-skating', 'label' => 'Roller skating'],
        ['name' => 'classic-roller-skiing', 'label' => 'Classic roller skiing'],
        ['name' => 'freestyle-roller-skiing', 'label' => 'Freestyle roller skiing'],
        ['name' => 'rowing', 'label' => 'Rowing'],
        ['name' => 'rugby', 'label' => 'Rugby'],
        ['name' => 'rucking', 'label' => 'Rucking'],
        ['name' => 'show', 'label' => 'Show'],
        ['name' => 'shooting-indoor', 'label' => 'Shooting (indoor)'],
        ['name' => 'shooting-outdoor', 'label' => 'Shooting (outdoor)'],
        ['name' => 'skateboarding', 'label' => 'Skateboarding'],
        ['name' => 'skating', 'label' => 'Skating'],
        ['name' => 'ski-machine', 'label' => 'Ski machine'],
        ['name' => 'snowboarding', 'label' => 'Snowboarding'],
        ['name' => 'snowshoe-trekking', 'label' => 'Snowshoe trekking'],
        ['name' => 'soccer', 'label' => 'Soccer'],
        ['name' => 'spinning', 'label' => 'Spinning'],
        ['name' => 'sup', 'label' => 'SUP'],
        ['name' => 'squash', 'label' => 'Squash'],
        ['name' => 'stair-workout', 'label' => 'Stair workout'],
        ['name' => 'street', 'label' => 'Street'],
        ['name' => 'strength-training', 'label' => 'Strength training'],
        ['name' => 'stretching', 'label' => 'Stretching'],
        ['name' => 'swimming', 'label' => 'Swimming'],
        ['name' => 'table-tennis', 'label' => 'Table tennis'],
        ['name' => 'taekwondo', 'label' => 'Taekwondo'],
        ['name' => 'telemark-skiing', 'label' => 'Telemark skiing'],
        ['name' => 'tennis', 'label' => 'Tennis'],
        ['name' => 'track-and-field-running', 'label' => 'Track&field running'],
        ['name' => 'treadmill-running', 'label' => 'Treadmill running'],
        ['name' => 'triathlon', 'label' => 'Triathlon'],
        ['name' => 'trotting', 'label' => 'Trotting'],
        ['name' => 'ultimate', 'label' => 'Ultimate'],
        ['name' => 'ultra-running', 'label' => 'Ultra running'],
        ['name' => 'climbing-indoor', 'label' => 'Climbing (indoor)'],
        ['name' => 'climbing-outdoor', 'label' => 'Climbing (outdoor)'],
        ['name' => 'volleyball', 'label' => 'Volleyball'],
        ['name' => 'walking', 'label' => 'Walking'],
        ['name' => 'water-sports', 'label' => 'Water sports'],
        ['name' => 'water-running', 'label' => 'Water running'],
        ['name' => 'canoeing', 'label' => 'Canoeing'],
        ['name' => 'kayaking', 'label' => 'Kayaking'],
        ['name' => 'kitesurfing', 'label' => 'Kitesurfing'],
        ['name' => 'sailing', 'label' => 'Sailing'],
        ['name' => 'surfing', 'label' => 'Surfing'],
        ['name' => 'wakeboarding', 'label' => 'Wakeboarding'],
        ['name' => 'water-skiing', 'label' => 'Water skiing'],
        ['name' => 'windsurfing', 'label' => 'Windsurfing'],
        ['name' => 'classic-xc-skiing', 'label' => 'Classic XC skiing'],
        ['name' => 'freestyle-xc-skiing', 'label' => 'Freestyle XC skiing'],
        ['name' => 'yoga', 'label' => 'Yoga'],
    ];

    public function run(): void
    {
        foreach ($this->sportTypes as $sportType) {
            SportType::firstOrCreate(
                ['name' => $sportType['name']],
                ['label' => $sportType['label']],
            );
        }
    }
}
