UPDATE external_sport_type_mappings esm
JOIN data_sources ds ON ds.id = esm.data_source_id
SET esm.external_id = CASE esm.external_name
    WHEN 'RUNNING' THEN '1'
    WHEN 'CYCLING' THEN '2'
    WHEN 'WALKING' THEN '3'
    WHEN 'MOUNTAIN_BIKING' THEN '5'
    WHEN 'STRENGTH_TRAINING' THEN '15'
    WHEN 'TREADMILL_RUNNING' THEN '17'
    WHEN 'INDOOR_CYCLING' THEN '18'
    WHEN 'HIIT' THEN '34'
    WHEN 'BOOTCAMP' THEN '58'
    WHEN 'OTHER_INDOOR' THEN '83'
END
WHERE ds.name = 'polar'
  AND esm.external_name IN ('BOOTCAMP', 'CYCLING', 'HIIT', 'INDOOR_CYCLING', 'MOUNTAIN_BIKING', 'OTHER_INDOOR', 'RUNNING', 'STRENGTH_TRAINING', 'TREADMILL_RUNNING', 'WALKING');
