; /etc/supervisor/conf.d/trainingsdata-worker.conf
[program:trainingsdata-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/trainingsdata/artisan queue:work --sleep=3 --tries=1 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/trainingsdata/storage/logs/worker.log
stopwaitsecs=3600
